### ISSUE TITLE
Write script to authenticate with the Authorization Code workflow.

### ISSUE THREAD

**Issue by wtanner** [wtanner/spotify-utils#5]
## Summary
The goal of this issue is to figure out how the authorization flow works for Authorization Code flow, and build a simple working example using the Python standard library.

## Exit Criteria
* Script that gets an access token and a refresh token with the OAuth scopes 'playlist-read-private' and 'playlist-modify-private'

## Notes
See: https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow

**Comment by evanH13** [comment]
This is in progress, currently working researching how to access the localhost redirect_uri.
